### ISSUE TITLE
Docker Compose?

### ISSUE THREAD

**Issue by poperigby** [almir/docker-webhook#19]
How can I format this to make it work in a `docker-compose.yml`?

**Comment by almir** [comment]
I'm not sure what is it you need exactly, but maybe this could help: https://github.com/almir/docker-webhook/issues/2#issuecomment-254469814

**Comment by poperigby** [comment]
Yeah, that helps. It should look something like this I think:

```
version: '3'
services:
  webhook:
    container_name: webhook
    image: kachkaev/webhook
    volumes:
      - '/path/to/hooks/on/host:/etc/webhook'
      - '/path/to/scripts/on/host:/opt/scripts'
      - '/path/to/app/on/host:/opt/app'
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - '9000:9000'
    command: 
      - "-verbose"
      - "-hooks=/etc/webhook/hooks.json"
      - "-hotreload"
```

Thanks!
