### ISSUE TITLE
Create a docker-compose file

### ISSUE THREAD

**Issue by federicociro** [almir/docker-webhook#24]
Hi, it would be nice to have and maintain a docker-compose file for the build.

**Comment by maxkratz** [comment]
> Hi, it would be nice to have and maintain a docker-compose file for the build.

Maybe this snipped helps you find inspiration:
```
  webhook:
    image: almir/webhook:2.8.0
    command: -verbose -hooks=/etc/webhook/hooks.json -hotreload
    restart: unless-stopped
    volumes:
      - './webhook.json:/etc/webhook/hooks.json:ro'
      # TODO: mount some scripts to be called via the webhook binary etc.
    networks:
      - default
```
